// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIzyPCLl0LndyaYPpqKnP0szfM69bX-o',
    appId: '1:995401456959:web:320436a517454e00f6c78a',
    messagingSenderId: '995401456959',
    projectId: 'solo-leveling-gym',
    authDomain: 'solo-leveling-gym.firebaseapp.com',
    databaseURL: 'https://solo-leveling-gym-default-rtdb.firebaseio.com',
    storageBucket: 'solo-leveling-gym.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgJlxPRvLMHpLKpFrLIzU95GovcZ0dt_Y',
    appId: '1:995401456959:android:f1378734101f9f6ff6c78a',
    messagingSenderId: '995401456959',
    projectId: 'solo-leveling-gym',
    databaseURL: 'https://solo-leveling-gym-default-rtdb.firebaseio.com',
    storageBucket: 'solo-leveling-gym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZq0vs1m9PJHdExD18Bx4MvWPS-xPWRvE',
    appId: '1:995401456959:ios:e4efcd3969060f1ff6c78a',
    messagingSenderId: '995401456959',
    projectId: 'solo-leveling-gym',
    databaseURL: 'https://solo-leveling-gym-default-rtdb.firebaseio.com',
    storageBucket: 'solo-leveling-gym.firebasestorage.app',
    iosBundleId: 'com.example.soloLevelingGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZq0vs1m9PJHdExD18Bx4MvWPS-xPWRvE',
    appId: '1:995401456959:ios:e4efcd3969060f1ff6c78a',
    messagingSenderId: '995401456959',
    projectId: 'solo-leveling-gym',
    databaseURL: 'https://solo-leveling-gym-default-rtdb.firebaseio.com',
    storageBucket: 'solo-leveling-gym.firebasestorage.app',
    iosBundleId: 'com.example.soloLevelingGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgIzyPCLl0LndyaYPpqKnP0szfM69bX-o',
    appId: '1:995401456959:web:83e9c6cd82e7139af6c78a',
    messagingSenderId: '995401456959',
    projectId: 'solo-leveling-gym',
    authDomain: 'solo-leveling-gym.firebaseapp.com',
    databaseURL: 'https://solo-leveling-gym-default-rtdb.firebaseio.com',
    storageBucket: 'solo-leveling-gym.firebasestorage.app',
  );
}
